name: Test IPython beamline profiles
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  testing_beamline_profiles:
    name: Test profile

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f  # v0.10.0
        with:
          pixi-version: v0.71.3
          cache: false
          environments: test

      - name: Run pytest
        run: pixi run tests
